chaos.monkey.enabled=true
chaos.monkey.watcher.controller=true
chaos.monkey.watcher.rest-controller=true
chaos.monkey.watcher.service=true
chaos.monkey.watcher.repository=false
chaos.monkey.assaults.level=5
chaos.monkey.assaults.deterministic=false
chaos.monkey.assaults.latency-active=false
chaos.monkey.assaults.latency-range-start=1000
chaos.monkey.assaults.latency-range-end=3000
chaos.monkey.assaults.exceptions-active=false
chaos.monkey.assaults.kill-application-active=false
management.endpoint.chaosmonkey.enabled=true
management.endpoints.web.exposure.include=health,chaosmonkey,metrics
